// export default {
//   env: 'development',
//   port: 4540,
//   DefaultEndpointsProtocol: 'https',
//   azureAccountName:"newbotstore",
//   azureAccountKey:"d5OhJ9V4WjwyUGTXrmm3KOC2hS5IYzEf6unfYmZrJ3Dzh3fhSEgaLjXVeU453eCAioJEjNTUKGpPPuP7quRUAw==",
//   EndpointSuffix: "core.windows.net",
//   elasticPvt: "http://172.16.6.4:9200/",
//   elasticPublic: "http://20.67.27.3:9200/",
//   mySqlPublic: "20.67.26.248",
//   mySqlPvt: "172.16.6.5",
//   mySqlPort:"3306",
//   mySqlUserName:"uniops",
//   mySqlPassword: "Tcz@dmin@123#",
//   graphApiEndpoint: "https://graph.microsoft.com/beta/me",
//   sendGridApiKey: "SG.qJpCFjtHQYWfCb1p9fSSaA.8GfTcsC2-O39H82h2Tx48Y-UdAGIO3vC73H69sTVmH",
//   // sendGridApiKey: "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",
//   sendGridFrom: "botstore@automationfactory.com",
//   ccSendGrid:"automation.factory@unilever.com",
//   baseUrl: "https://automation-qa.unilever.com",
//   fileUpload: "https://newbotstore.blob.core.windows.net/botstorevideo",
//   apporvalPortalLink:"https://automation-dev.unilever.com/approvals",
//   fetchBlobUrl: "https://newbotstore.blob.core.windows.net/botstorevideo",
// };
// // botstore@automationfactory.com   HUl.Admin@automationfactory.com

export default {
  env: 'development',
  port: 4540,
  DefaultEndpointsProtocol: 'https',
  azureAccountName:"bnlwestgunileveraf01091",
  azureAccountKey:"AJlz6P5C6jPKNYZqFq8GGFMl/3Vbu2IMBJPlIuDz55YBjI5O/M8OiM7q5XxDG63wjGbLvMUwZovN6m8gyQyaKA==",
  EndpointSuffix: "core.windows.net",
  elasticPvt: "http://10.234.248.53:9200/",
  elasticPublic: "http://10.234.248.53:9200/",
  mySqlPublic: "10.234.248.52",
  mySqlPvt: "10.234.248.52",
  mySqlPort:"3306",
  mySqlUserName:"uniops",
  mySqlPassword: "ZseXdr123!",
  graphApiEndpoint: "https://graph.microsoft.com/beta/me",
  sendGridApiKey: "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",
  sendGridFrom: "botstore@automationfactory.com",
  ccSendGrid:"automation.factory@unilever.com",
  baseUrl: "https://automation-qa.unilever.com",
  fileUpload: "https://bnlwestgunileveraf01091.blob.core.windows.net/botstorevideo",
  apporvalPortalLink:"https://automation-qa.unilever.com/approvals",
  fetchBlobUrl: "https://bnlwestgunileveraf01091.blob.core.windows.net/botstorevideoo",
};
// botstore@automationfactory.com   HUl.Admin@automationfactory.com
