export default {
  env: 'production',
  port: 4540,
  DefaultEndpointsProtocol: 'https',
  azureAccountName: 'bnlwestgunileveraf01092',
  azureAccountKey:
    '6nPRRkvko6qzu/nE+oWjTbwJl4weLNYQ7/d19sJ7xHKz6jnJYh39r0hsOt8BpxA37+shyNVIbDcohKccRNWbWQ==',
  EndpointSuffix: 'core.windows.net',
  elasticPvt: 'http://10.234.240.62:9200/',
  mySqlPvt: '10.234.240.60',
  mySqlPort: '3306',
  mySqlUserName: 'uniops',
  elasticPublic: 'http://10.234.240.62:9200/',
  mySqlPassword: 'ZseXdr321!',
  graphApiEndpoint: 'https://graph.microsoft.com/beta/me',
  sendGridApiKey: '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',
  sendGridFrom: 'botstore@automationfactory.com',
  ccSendGrid: 'automation.factory@unilever.com',
  baseUrl: 'https://automation.unilever.com',
  fileUpload: 'https://bnlwestgunileveraf01092.blob.core.windows.net/botstorevideo',
  apporvalPortalLink: 'https://automation.unilever.com/approvals',
  fetchBlobUrl: 'https://bnlwestgunileveraf01092.blob.core.windows.net/botstorevideo',
};
//sendGridFrom: "HUl.Admin@automationfactory.com",
